export interface CatalogModel {
  id: string;
  name: string;
  description: string;
  tags: string[];
  sizes: CatalogVariant[];
  pulls: string;
  updated: string;
  capabilities: string[];
}

export interface CatalogVariant {
  tag: string;
  params: string;
  size: string;
  sizeBytes: number;
  quant: string;
}

function gb(n: number): number {
  return Math.round(n * 1024 * 1024 * 1024);
}

// Bilinen bağlam (context) pencereleri — token cinsinden. Model ailesi adına göre eşleşir.
// Canlı katalog (ollama.com) bağlam uzunluğunu vermediği için bu sabit harita kullanılır.
// En uzun eşleşen önek kazanır (örn. "qwen2.5-coder" > "qwen2.5").
export const CONTEXT_WINDOWS: Record<string, number> = {
  "llama3.2": 131072,
  "llama3.3": 131072,
  "llama3.1": 131072,
  "llama3": 8192,
  "llama2": 4096,
  "gemma3n": 32768,
  "gemma3": 131072,
  "gemma4": 131072,
  "gemma2": 8192,
  "gemma": 8192,
  "qwen3": 40960,
  "qwen2.5-coder": 131072,
  "qwen2.5": 131072,
  "qwen2": 32768,
  "qwq": 131072,
  "phi4-mini": 131072,
  "phi4": 16384,
  "phi3.5": 131072,
  "phi3": 131072,
  "mistral-nemo": 131072,
  "mistral-small": 32768,
  "mistral-large": 131072,
  "mistral": 32768,
  "mixtral": 32768,
  "deepseek-r1": 131072,
  "deepseek-coder-v2": 131072,
  "deepseek-v2.5": 131072,
  "codellama": 16384,
  "codestral": 32768,
  "codegemma": 8192,
  "starcoder2": 16384,
  "command-r-plus": 131072,
  "command-r": 131072,
  "llava-llama3": 8192,
  "llava": 4096,
  "moondream": 2048,
  "bakllava": 4096,
  "tinyllama": 2048,
  "smollm2": 8192,
  "granite-code": 131072,
  "yi": 4096,
  "solar": 4096,
  "wizardlm2": 65536,
  "internlm2": 32768,
  "glm4": 131072,
  "olmo": 4096,
  "nomic-embed-text": 8192,
  "mxbai-embed-large": 512,
  "all-minilm": 512,
};

/** Model id'sine (aile adı) göre bilinen bağlam penceresini döndürür; en uzun eşleşen önek kazanır. */
export function lookupContextWindow(modelId: string): number | null {
  const id = modelId.toLowerCase();
  let best: string | null = null;
  for (const key of Object.keys(CONTEXT_WINDOWS)) {
    if (id === key || id.startsWith(key)) {
      if (!best || key.length > best.length) best = key;
    }
  }
  return best ? CONTEXT_WINDOWS[best] : null;
}

/** Token sayısını okunabilir bağlam etiketine çevirir (örn. 131072 → "128K"). */
export function formatContext(tokens: number): string {
  if (tokens >= 1_048_576) return `${Math.round(tokens / 1_048_576)}M`;
  if (tokens >= 1024) return `${Math.round(tokens / 1024)}K`;
  return String(tokens);
}

export const MODEL_CATALOG: CatalogModel[] = [
  {
    id: "llama3.2",
    name: "Llama 3.2",
    description: "Meta'nın en yeni hafif modeli. Hızlı ve verimli, günlük kullanım için ideal.",
    tags: ["popüler", "hafif", "çok yönlü"],
    pulls: "42.5M",
    updated: "2025-05",
    capabilities: ["completion", "tools"],
    sizes: [
      { tag: "1b", params: "1B", size: "1.3 GB", sizeBytes: gb(1.3), quant: "Q4_0" },
      { tag: "3b", params: "3B", size: "2.0 GB", sizeBytes: gb(2.0), quant: "Q4_0" },
    ],
  },
  {
    id: "llama3.3",
    name: "Llama 3.3",
    description: "Meta'nın yüksek performanslı çok dilli modeli. Karmaşık görevlerde güçlü.",
    tags: ["popüler", "güçlü", "çok dilli"],
    pulls: "18.2M",
    updated: "2025-04",
    capabilities: ["completion", "tools"],
    sizes: [
      { tag: "70b", params: "70B", size: "43 GB", sizeBytes: gb(43), quant: "Q4_0" },
    ],
  },
  {
    id: "llama3.1",
    name: "Llama 3.1",
    description: "Meta'nın geniş bağlam pencereli modeli. 128K token desteği ile uzun dökümanlar için ideal.",
    tags: ["popüler", "uzun bağlam", "çok dilli"],
    pulls: "35.8M",
    updated: "2025-01",
    capabilities: ["completion", "tools"],
    sizes: [
      { tag: "8b", params: "8B", size: "4.7 GB", sizeBytes: gb(4.7), quant: "Q4_0" },
      { tag: "70b", params: "70B", size: "43 GB", sizeBytes: gb(43), quant: "Q4_0" },
      { tag: "405b", params: "405B", size: "229 GB", sizeBytes: gb(229), quant: "Q4_0" },
    ],
  },
  {
    id: "gemma3",
    name: "Gemma 3",
    description: "Google DeepMind'ın güçlü açık modeli. Çok dilli, hızlı ve doğru.",
    tags: ["google", "çok dilli", "verimli"],
    pulls: "8.7M",
    updated: "2025-05",
    capabilities: ["completion", "tools"],
    sizes: [
      { tag: "1b", params: "1B", size: "815 MB", sizeBytes: gb(0.8), quant: "Q4_0" },
      { tag: "4b", params: "4B", size: "3.3 GB", sizeBytes: gb(3.3), quant: "Q4_0" },
      { tag: "12b", params: "12B", size: "8.1 GB", sizeBytes: gb(8.1), quant: "Q4_0" },
      { tag: "27b", params: "27B", size: "17 GB", sizeBytes: gb(17), quant: "Q4_0" },
    ],
  },
  {
    id: "gemma4",
    name: "Gemma 4",
    description: "Google'ın en yeni nesil modeli. Gelişmiş muhakeme ve görsel anlama yeteneği.",
    tags: ["google", "yeni", "multimodal"],
    pulls: "2.1M",
    updated: "2025-06",
    capabilities: ["completion", "tools", "vision"],
    sizes: [
      { tag: "12b", params: "12B", size: "8.1 GB", sizeBytes: gb(8.1), quant: "Q4_0" },
      { tag: "27b", params: "27B", size: "17 GB", sizeBytes: gb(17), quant: "Q4_0" },
    ],
  },
  {
    id: "gemma2",
    name: "Gemma 2",
    description: "Google'ın ikinci nesil açık modeli. Dengeli performans ve verimlilik.",
    tags: ["google", "dengeli", "verimli"],
    pulls: "12.4M",
    updated: "2024-10",
    capabilities: ["completion"],
    sizes: [
      { tag: "2b", params: "2B", size: "1.6 GB", sizeBytes: gb(1.6), quant: "Q4_0" },
      { tag: "9b", params: "9B", size: "5.4 GB", sizeBytes: gb(5.4), quant: "Q4_0" },
      { tag: "27b", params: "27B", size: "16 GB", sizeBytes: gb(16), quant: "Q4_0" },
    ],
  },
  {
    id: "qwen3",
    name: "Qwen 3",
    description: "Alibaba'nın güçlü modeli. Düşünme ve kodlama konusunda çok yetenekli.",
    tags: ["düşünme", "kodlama", "güçlü"],
    pulls: "15.3M",
    updated: "2025-05",
    capabilities: ["completion", "tools"],
    sizes: [
      { tag: "0.6b", params: "0.6B", size: "505 MB", sizeBytes: gb(0.5), quant: "Q4_0" },
      { tag: "1.7b", params: "1.7B", size: "1.2 GB", sizeBytes: gb(1.2), quant: "Q4_0" },
      { tag: "4b", params: "4B", size: "2.6 GB", sizeBytes: gb(2.6), quant: "Q4_0" },
      { tag: "8b", params: "8B", size: "5.2 GB", sizeBytes: gb(5.2), quant: "Q4_0" },
      { tag: "14b", params: "14B", size: "9.0 GB", sizeBytes: gb(9.0), quant: "Q4_0" },
      { tag: "30b", params: "30B", size: "19 GB", sizeBytes: gb(19), quant: "Q4_0" },
      { tag: "32b", params: "32B", size: "20 GB", sizeBytes: gb(20), quant: "Q4_0" },
    ],
  },
  {
    id: "qwen2.5",
    name: "Qwen 2.5",
    description: "Alibaba'nın kararlı genel amaçlı modeli. Geniş dil desteği ve güçlü performans.",
    tags: ["çok dilli", "kararlı", "genel"],
    pulls: "22.7M",
    updated: "2025-03",
    capabilities: ["completion", "tools"],
    sizes: [
      { tag: "0.5b", params: "0.5B", size: "398 MB", sizeBytes: gb(0.39), quant: "Q4_0" },
      { tag: "1.5b", params: "1.5B", size: "986 MB", sizeBytes: gb(0.96), quant: "Q4_0" },
      { tag: "3b", params: "3B", size: "1.9 GB", sizeBytes: gb(1.9), quant: "Q4_0" },
      { tag: "7b", params: "7B", size: "4.7 GB", sizeBytes: gb(4.7), quant: "Q4_0" },
      { tag: "14b", params: "14B", size: "9.0 GB", sizeBytes: gb(9.0), quant: "Q4_0" },
      { tag: "32b", params: "32B", size: "20 GB", sizeBytes: gb(20), quant: "Q4_0" },
      { tag: "72b", params: "72B", size: "47 GB", sizeBytes: gb(47), quant: "Q4_0" },
    ],
  },
  {
    id: "qwen2.5-coder",
    name: "Qwen 2.5 Coder",
    description: "Alibaba'nın kod odaklı modeli. Kod üretimi, analizi ve düzeltme için optimize.",
    tags: ["kodlama", "alibaba", "uzman"],
    pulls: "9.8M",
    updated: "2025-02",
    capabilities: ["completion", "tools"],
    sizes: [
      { tag: "0.5b", params: "0.5B", size: "398 MB", sizeBytes: gb(0.39), quant: "Q4_0" },
      { tag: "1.5b", params: "1.5B", size: "986 MB", sizeBytes: gb(0.96), quant: "Q4_0" },
      { tag: "3b", params: "3B", size: "1.9 GB", sizeBytes: gb(1.9), quant: "Q4_0" },
      { tag: "7b", params: "7B", size: "4.7 GB", sizeBytes: gb(4.7), quant: "Q4_0" },
      { tag: "14b", params: "14B", size: "9.0 GB", sizeBytes: gb(9.0), quant: "Q4_0" },
      { tag: "32b", params: "32B", size: "20 GB", sizeBytes: gb(20), quant: "Q4_0" },
    ],
  },
  {
    id: "phi4",
    name: "Phi 4",
    description: "Microsoft'un kompakt ama güçlü modeli. Küçük boyutuyla şaşırtıcı performans.",
    tags: ["microsoft", "kompakt", "verimli"],
    pulls: "6.8M",
    updated: "2025-04",
    capabilities: ["completion", "tools"],
    sizes: [
      { tag: "14b", params: "14B", size: "9.1 GB", sizeBytes: gb(9.1), quant: "Q4_0" },
    ],
  },
  {
    id: "phi4-mini",
    name: "Phi 4 Mini",
    description: "Microsoft'un en hafif modeli. Düşük kaynaklı sistemlerde bile etkili.",
    tags: ["microsoft", "hafif", "hızlı"],
    pulls: "4.2M",
    updated: "2025-05",
    capabilities: ["completion", "tools"],
    sizes: [
      { tag: "3.8b", params: "3.8B", size: "2.5 GB", sizeBytes: gb(2.5), quant: "Q4_0" },
    ],
  },
  {
    id: "phi3",
    name: "Phi 3",
    description: "Microsoft'un önceki nesil kompakt modeli. Küçük ama yetenekli.",
    tags: ["microsoft", "kompakt", "kararlı"],
    pulls: "11.5M",
    updated: "2024-08",
    capabilities: ["completion"],
    sizes: [
      { tag: "3.8b", params: "3.8B", size: "2.2 GB", sizeBytes: gb(2.2), quant: "Q4_0" },
      { tag: "14b", params: "14B", size: "7.9 GB", sizeBytes: gb(7.9), quant: "Q4_0" },
    ],
  },
  {
    id: "phi3.5",
    name: "Phi 3.5",
    description: "Microsoft'un geliştirilmiş Phi modeli. Daha iyi muhakeme ve çok dilli destek.",
    tags: ["microsoft", "gelişmiş", "çok dilli"],
    pulls: "5.1M",
    updated: "2024-10",
    capabilities: ["completion", "vision"],
    sizes: [
      { tag: "3.8b", params: "3.8B", size: "2.2 GB", sizeBytes: gb(2.2), quant: "Q4_0" },
    ],
  },
  {
    id: "mistral",
    name: "Mistral",
    description: "Mistral AI'ın temel modeli. Dengeli performans ve hız sunar.",
    tags: ["popüler", "dengeli", "fransız"],
    pulls: "22.1M",
    updated: "2025-03",
    capabilities: ["completion", "tools"],
    sizes: [
      { tag: "7b", params: "7B", size: "4.1 GB", sizeBytes: gb(4.1), quant: "Q4_0" },
    ],
  },
  {
    id: "mistral-nemo",
    name: "Mistral Nemo",
    description: "Mistral ve NVIDIA ortaklığıyla geliştirilen 12B model. Uzun bağlam desteği.",
    tags: ["mistral", "nvidia", "uzun bağlam"],
    pulls: "7.3M",
    updated: "2024-12",
    capabilities: ["completion", "tools"],
    sizes: [
      { tag: "12b", params: "12B", size: "7.1 GB", sizeBytes: gb(7.1), quant: "Q4_0" },
    ],
  },
  {
    id: "mistral-small",
    name: "Mistral Small",
    description: "Mistral AI'ın hafif kurumsal modeli. Hızlı yanıt ve araç kullanımı.",
    tags: ["mistral", "kurumsal", "hızlı"],
    pulls: "4.8M",
    updated: "2025-02",
    capabilities: ["completion", "tools"],
    sizes: [
      { tag: "22b", params: "22B", size: "13 GB", sizeBytes: gb(13), quant: "Q4_0" },
      { tag: "24b", params: "24B", size: "14 GB", sizeBytes: gb(14), quant: "Q4_0" },
    ],
  },
  {
    id: "mixtral",
    name: "Mixtral",
    description: "Mistral'ın Mixture of Experts modeli. 8 uzman ile yüksek performans, düşük gecikme.",
    tags: ["MoE", "mistral", "güçlü"],
    pulls: "8.9M",
    updated: "2024-06",
    capabilities: ["completion"],
    sizes: [
      { tag: "8x7b", params: "8x7B", size: "26 GB", sizeBytes: gb(26), quant: "Q4_0" },
      { tag: "8x22b", params: "8x22B", size: "80 GB", sizeBytes: gb(80), quant: "Q4_0" },
    ],
  },
  {
    id: "deepseek-r1",
    name: "DeepSeek R1",
    description: "DeepSeek'in muhakeme odaklı modeli. Karmaşık problemleri adım adım çözer.",
    tags: ["düşünme", "muhakeme", "güçlü"],
    pulls: "28.6M",
    updated: "2025-04",
    capabilities: ["completion"],
    sizes: [
      { tag: "1.5b", params: "1.5B", size: "1.1 GB", sizeBytes: gb(1.1), quant: "Q4_0" },
      { tag: "7b", params: "7B", size: "4.7 GB", sizeBytes: gb(4.7), quant: "Q4_0" },
      { tag: "8b", params: "8B", size: "4.9 GB", sizeBytes: gb(4.9), quant: "Q4_0" },
      { tag: "14b", params: "14B", size: "9.0 GB", sizeBytes: gb(9.0), quant: "Q4_0" },
      { tag: "32b", params: "32B", size: "20 GB", sizeBytes: gb(20), quant: "Q4_0" },
      { tag: "70b", params: "70B", size: "43 GB", sizeBytes: gb(43), quant: "Q4_0" },
      { tag: "671b", params: "671B", size: "404 GB", sizeBytes: gb(404), quant: "Q4_0" },
    ],
  },
  {
    id: "deepseek-coder-v2",
    name: "DeepSeek Coder V2",
    description: "DeepSeek'in kod üretim modeli. Kodlama ve matematik konusunda uzmanlaşmış.",
    tags: ["kodlama", "deepseek", "MoE"],
    pulls: "5.2M",
    updated: "2024-09",
    capabilities: ["completion"],
    sizes: [
      { tag: "16b", params: "16B", size: "8.9 GB", sizeBytes: gb(8.9), quant: "Q4_0" },
      { tag: "236b", params: "236B", size: "133 GB", sizeBytes: gb(133), quant: "Q4_0" },
    ],
  },
  {
    id: "deepseek-v2.5",
    name: "DeepSeek V2.5",
    description: "DeepSeek'in genel amaçlı MoE modeli. Chat ve kodlama yetenekleri birleşik.",
    tags: ["deepseek", "MoE", "genel"],
    pulls: "3.4M",
    updated: "2024-11",
    capabilities: ["completion"],
    sizes: [
      { tag: "236b", params: "236B", size: "133 GB", sizeBytes: gb(133), quant: "Q4_0" },
    ],
  },
  {
    id: "codellama",
    name: "Code Llama",
    description: "Meta'nın kod odaklı modeli. Programlama ve kod analizi için optimize edilmiş.",
    tags: ["kodlama", "meta", "uzman"],
    pulls: "9.4M",
    updated: "2024-12",
    capabilities: ["completion"],
    sizes: [
      { tag: "7b", params: "7B", size: "3.8 GB", sizeBytes: gb(3.8), quant: "Q4_0" },
      { tag: "13b", params: "13B", size: "7.4 GB", sizeBytes: gb(7.4), quant: "Q4_0" },
      { tag: "34b", params: "34B", size: "19 GB", sizeBytes: gb(19), quant: "Q4_0" },
    ],
  },
  {
    id: "codestral",
    name: "Codestral",
    description: "Mistral AI'ın kod için özel olarak eğitilmiş modeli. 80+ dil desteği.",
    tags: ["kodlama", "mistral", "çok dilli"],
    pulls: "3.6M",
    updated: "2025-01",
    capabilities: ["completion"],
    sizes: [
      { tag: "22b", params: "22B", size: "13 GB", sizeBytes: gb(13), quant: "Q4_0" },
    ],
  },
  {
    id: "codegemma",
    name: "CodeGemma",
    description: "Google'ın kod odaklı Gemma modeli. Kod tamamlama ve üretimde uzman.",
    tags: ["kodlama", "google", "uzman"],
    pulls: "4.1M",
    updated: "2024-08",
    capabilities: ["completion"],
    sizes: [
      { tag: "2b", params: "2B", size: "1.6 GB", sizeBytes: gb(1.6), quant: "Q4_0" },
      { tag: "7b", params: "7B", size: "5.0 GB", sizeBytes: gb(5.0), quant: "Q4_0" },
    ],
  },
  {
    id: "starcoder2",
    name: "StarCoder 2",
    description: "BigCode'un kod üretim modeli. 600+ programlama dilini destekler.",
    tags: ["kodlama", "açık kaynak", "çok dilli"],
    pulls: "3.2M",
    updated: "2024-09",
    capabilities: ["completion"],
    sizes: [
      { tag: "3b", params: "3B", size: "1.7 GB", sizeBytes: gb(1.7), quant: "Q4_0" },
      { tag: "7b", params: "7B", size: "4.0 GB", sizeBytes: gb(4.0), quant: "Q4_0" },
      { tag: "15b", params: "15B", size: "9.1 GB", sizeBytes: gb(9.1), quant: "Q4_0" },
    ],
  },
  {
    id: "llava",
    name: "LLaVA",
    description: "Görsel anlama modeli. Resimleri analiz edebilir ve açıklayabilir.",
    tags: ["multimodal", "görsel", "analiz"],
    pulls: "7.1M",
    updated: "2024-11",
    capabilities: ["completion", "vision"],
    sizes: [
      { tag: "7b", params: "7B", size: "4.7 GB", sizeBytes: gb(4.7), quant: "Q4_0" },
      { tag: "13b", params: "13B", size: "8.0 GB", sizeBytes: gb(8.0), quant: "Q4_0" },
      { tag: "34b", params: "34B", size: "20 GB", sizeBytes: gb(20), quant: "Q4_0" },
    ],
  },
  {
    id: "llava-llama3",
    name: "LLaVA Llama 3",
    description: "Llama 3 tabanlı görsel model. Daha iyi dil anlama ile görsel analiz.",
    tags: ["multimodal", "llama3", "görsel"],
    pulls: "2.8M",
    updated: "2024-09",
    capabilities: ["completion", "vision"],
    sizes: [
      { tag: "8b", params: "8B", size: "5.5 GB", sizeBytes: gb(5.5), quant: "Q4_0" },
    ],
  },
  {
    id: "moondream",
    name: "Moondream",
    description: "Ultra hafif görsel model. Düşük kaynaklı cihazlarda bile görüntü anlama.",
    tags: ["multimodal", "hafif", "görsel"],
    pulls: "3.5M",
    updated: "2024-10",
    capabilities: ["completion", "vision"],
    sizes: [
      { tag: "1.8b", params: "1.8B", size: "1.7 GB", sizeBytes: gb(1.7), quant: "Q4_0" },
    ],
  },
  {
    id: "bakllava",
    name: "BakLLaVA",
    description: "Mistral tabanlı görsel anlama modeli. Resim ve metin birlikte işleme.",
    tags: ["multimodal", "mistral", "görsel"],
    pulls: "1.9M",
    updated: "2024-06",
    capabilities: ["completion", "vision"],
    sizes: [
      { tag: "7b", params: "7B", size: "4.5 GB", sizeBytes: gb(4.5), quant: "Q4_0" },
    ],
  },
  {
    id: "command-r",
    name: "Command R",
    description: "Cohere'ın RAG ve araç kullanımı için optimize edilmiş modeli.",
    tags: ["RAG", "araçlar", "kurumsal"],
    pulls: "2.8M",
    updated: "2024-11",
    capabilities: ["completion", "tools"],
    sizes: [
      { tag: "35b", params: "35B", size: "20 GB", sizeBytes: gb(20), quant: "Q4_0" },
    ],
  },
  {
    id: "command-r-plus",
    name: "Command R+",
    description: "Cohere'ın en güçlü modeli. Kurumsal RAG ve karmaşık görevler için tasarlanmış.",
    tags: ["RAG", "kurumsal", "güçlü"],
    pulls: "1.4M",
    updated: "2024-11",
    capabilities: ["completion", "tools"],
    sizes: [
      { tag: "104b", params: "104B", size: "60 GB", sizeBytes: gb(60), quant: "Q4_0" },
    ],
  },
  {
    id: "wizardlm2",
    name: "WizardLM 2",
    description: "Microsoft'un talimat takip modeli. Karmaşık talimatları doğru anlama ve uygulama.",
    tags: ["talimat", "microsoft", "güçlü"],
    pulls: "4.5M",
    updated: "2024-07",
    capabilities: ["completion"],
    sizes: [
      { tag: "7b", params: "7B", size: "4.1 GB", sizeBytes: gb(4.1), quant: "Q4_0" },
      { tag: "8x22b", params: "8x22B", size: "80 GB", sizeBytes: gb(80), quant: "Q4_0" },
    ],
  },
  {
    id: "dolphin-mixtral",
    name: "Dolphin Mixtral",
    description: "Sansürsüz ve yardımsever Mixtral tabanlı model. Geniş kullanım alanı.",
    tags: ["sansürsüz", "MoE", "çok yönlü"],
    pulls: "3.8M",
    updated: "2024-05",
    capabilities: ["completion"],
    sizes: [
      { tag: "8x7b", params: "8x7B", size: "26 GB", sizeBytes: gb(26), quant: "Q4_0" },
      { tag: "8x22b", params: "8x22B", size: "80 GB", sizeBytes: gb(80), quant: "Q4_0" },
    ],
  },
  {
    id: "nous-hermes2",
    name: "Nous Hermes 2",
    description: "Nous Research'ın talimat modeli. İyi yapılandırılmış ve tutarlı yanıtlar.",
    tags: ["talimat", "nous", "tutarlı"],
    pulls: "3.2M",
    updated: "2024-04",
    capabilities: ["completion"],
    sizes: [
      { tag: "10.7b", params: "10.7B", size: "6.1 GB", sizeBytes: gb(6.1), quant: "Q4_0" },
      { tag: "34b", params: "34B", size: "19 GB", sizeBytes: gb(19), quant: "Q4_0" },
    ],
  },
  {
    id: "openchat",
    name: "OpenChat",
    description: "Açık kaynak sohbet modeli. GPT-3.5 seviyesinde performans, yerel çalışma.",
    tags: ["sohbet", "açık kaynak", "verimli"],
    pulls: "3.9M",
    updated: "2024-03",
    capabilities: ["completion"],
    sizes: [
      { tag: "7b", params: "7B", size: "4.1 GB", sizeBytes: gb(4.1), quant: "Q4_0" },
    ],
  },
  {
    id: "zephyr",
    name: "Zephyr",
    description: "HuggingFace'in DPO ile eğitilmiş modeli. Yardımsever ve güvenli yanıtlar.",
    tags: ["huggingface", "DPO", "güvenli"],
    pulls: "4.7M",
    updated: "2024-02",
    capabilities: ["completion"],
    sizes: [
      { tag: "7b", params: "7B", size: "4.1 GB", sizeBytes: gb(4.1), quant: "Q4_0" },
    ],
  },
  {
    id: "neural-chat",
    name: "Neural Chat",
    description: "Intel tarafından optimize edilmiş sohbet modeli. Intel donanımında hızlı çalışır.",
    tags: ["intel", "sohbet", "optimize"],
    pulls: "2.6M",
    updated: "2024-01",
    capabilities: ["completion"],
    sizes: [
      { tag: "7b", params: "7B", size: "4.1 GB", sizeBytes: gb(4.1), quant: "Q4_0" },
    ],
  },
  {
    id: "solar",
    name: "Solar",
    description: "Upstage'in 10.7B modeli. Depth up-scaling ile yüksek performans.",
    tags: ["upstage", "verimli", "korece"],
    pulls: "2.3M",
    updated: "2024-04",
    capabilities: ["completion"],
    sizes: [
      { tag: "10.7b", params: "10.7B", size: "6.1 GB", sizeBytes: gb(6.1), quant: "Q4_0" },
    ],
  },
  {
    id: "yi",
    name: "Yi",
    description: "01.AI'ın güçlü çift dilli modeli. İngilizce ve Çince'de yüksek performans.",
    tags: ["çift dilli", "01ai", "güçlü"],
    pulls: "3.1M",
    updated: "2024-06",
    capabilities: ["completion"],
    sizes: [
      { tag: "6b", params: "6B", size: "3.5 GB", sizeBytes: gb(3.5), quant: "Q4_0" },
      { tag: "9b", params: "9B", size: "5.0 GB", sizeBytes: gb(5.0), quant: "Q4_0" },
      { tag: "34b", params: "34B", size: "19 GB", sizeBytes: gb(19), quant: "Q4_0" },
    ],
  },
  {
    id: "vicuna",
    name: "Vicuna",
    description: "ShareGPT sohbetleriyle eğitilmiş model. Doğal ve akıcı konuşma yeteneği.",
    tags: ["sohbet", "açık kaynak", "akıcı"],
    pulls: "4.1M",
    updated: "2024-01",
    capabilities: ["completion"],
    sizes: [
      { tag: "7b", params: "7B", size: "3.8 GB", sizeBytes: gb(3.8), quant: "Q4_0" },
      { tag: "13b", params: "13B", size: "7.4 GB", sizeBytes: gb(7.4), quant: "Q4_0" },
      { tag: "33b", params: "33B", size: "19 GB", sizeBytes: gb(19), quant: "Q4_0" },
    ],
  },
  {
    id: "orca-mini",
    name: "Orca Mini",
    description: "Küçük ama yetenekli model. Sınırlı kaynaklarla mantık yürütme.",
    tags: ["hafif", "muhakeme", "verimli"],
    pulls: "3.5M",
    updated: "2024-01",
    capabilities: ["completion"],
    sizes: [
      { tag: "3b", params: "3B", size: "1.9 GB", sizeBytes: gb(1.9), quant: "Q4_0" },
      { tag: "7b", params: "7B", size: "3.8 GB", sizeBytes: gb(3.8), quant: "Q4_0" },
      { tag: "13b", params: "13B", size: "7.4 GB", sizeBytes: gb(7.4), quant: "Q4_0" },
    ],
  },
  {
    id: "tinyllama",
    name: "TinyLlama",
    description: "1.1B parametreli ultra hafif model. Gömülü sistemler ve test için ideal.",
    tags: ["ultra hafif", "test", "gömülü"],
    pulls: "5.8M",
    updated: "2024-01",
    capabilities: ["completion"],
    sizes: [
      { tag: "1.1b", params: "1.1B", size: "638 MB", sizeBytes: gb(0.62), quant: "Q4_0" },
    ],
  },
  {
    id: "smollm2",
    name: "SmolLM 2",
    description: "HuggingFace'in ultra küçük modeli. Cihaz üstü çalışma için tasarlanmış.",
    tags: ["ultra hafif", "huggingface", "edge"],
    pulls: "2.7M",
    updated: "2025-01",
    capabilities: ["completion"],
    sizes: [
      { tag: "135m", params: "135M", size: "92 MB", sizeBytes: gb(0.09), quant: "Q4_0" },
      { tag: "360m", params: "360M", size: "229 MB", sizeBytes: gb(0.22), quant: "Q4_0" },
      { tag: "1.7b", params: "1.7B", size: "1.0 GB", sizeBytes: gb(1.0), quant: "Q4_0" },
    ],
  },
  {
    id: "llama2",
    name: "Llama 2",
    description: "Meta'nın klasik açık modeli. Geniş ekosistem ve topluluk desteği.",
    tags: ["meta", "klasik", "popüler"],
    pulls: "31.2M",
    updated: "2024-01",
    capabilities: ["completion"],
    sizes: [
      { tag: "7b", params: "7B", size: "3.8 GB", sizeBytes: gb(3.8), quant: "Q4_0" },
      { tag: "13b", params: "13B", size: "7.4 GB", sizeBytes: gb(7.4), quant: "Q4_0" },
      { tag: "70b", params: "70B", size: "39 GB", sizeBytes: gb(39), quant: "Q4_0" },
    ],
  },
  {
    id: "llama2-uncensored",
    name: "Llama 2 Uncensored",
    description: "Sansürsüz Llama 2 modeli. Kısıtlama olmadan serbest kullanım.",
    tags: ["sansürsüz", "meta", "serbest"],
    pulls: "6.2M",
    updated: "2024-01",
    capabilities: ["completion"],
    sizes: [
      { tag: "7b", params: "7B", size: "3.8 GB", sizeBytes: gb(3.8), quant: "Q4_0" },
    ],
  },
  {
    id: "falcon",
    name: "Falcon",
    description: "TII tarafından geliştirilen model. Geniş veri seti ile eğitilmiş, güçlü genel performans.",
    tags: ["TII", "güçlü", "genel"],
    pulls: "2.4M",
    updated: "2024-02",
    capabilities: ["completion"],
    sizes: [
      { tag: "7b", params: "7B", size: "3.8 GB", sizeBytes: gb(3.8), quant: "Q4_0" },
      { tag: "40b", params: "40B", size: "23 GB", sizeBytes: gb(23), quant: "Q4_0" },
      { tag: "180b", params: "180B", size: "102 GB", sizeBytes: gb(102), quant: "Q4_0" },
    ],
  },
  {
    id: "aya",
    name: "Aya",
    description: "Cohere'ın çok dilli modeli. 100+ dil desteği ile kapsayıcı AI.",
    tags: ["çok dilli", "cohere", "kapsayıcı"],
    pulls: "1.8M",
    updated: "2025-01",
    capabilities: ["completion"],
    sizes: [
      { tag: "8b", params: "8B", size: "4.8 GB", sizeBytes: gb(4.8), quant: "Q4_0" },
      { tag: "35b", params: "35B", size: "20 GB", sizeBytes: gb(20), quant: "Q4_0" },
    ],
  },
  {
    id: "granite-code",
    name: "Granite Code",
    description: "IBM'in kod modeli. Kurumsal yazılım geliştirme için güvenilir ve güvenli.",
    tags: ["kodlama", "IBM", "kurumsal"],
    pulls: "2.1M",
    updated: "2024-10",
    capabilities: ["completion"],
    sizes: [
      { tag: "3b", params: "3B", size: "2.0 GB", sizeBytes: gb(2.0), quant: "Q4_0" },
      { tag: "8b", params: "8B", size: "4.6 GB", sizeBytes: gb(4.6), quant: "Q4_0" },
      { tag: "20b", params: "20B", size: "12 GB", sizeBytes: gb(12), quant: "Q4_0" },
      { tag: "34b", params: "34B", size: "19 GB", sizeBytes: gb(19), quant: "Q4_0" },
    ],
  },
  {
    id: "nomic-embed-text",
    name: "Nomic Embed",
    description: "Metin gömme modeli. Arama ve benzerlik için vektör oluşturur.",
    tags: ["embedding", "arama", "araç"],
    pulls: "11.2M",
    updated: "2024-10",
    capabilities: ["completion"],
    sizes: [
      { tag: "latest", params: "137M", size: "274 MB", sizeBytes: gb(0.27), quant: "F16" },
    ],
  },
  {
    id: "mxbai-embed-large",
    name: "MxBai Embed Large",
    description: "Mixedbread'in büyük gömme modeli. Yüksek kaliteli semantik arama vektörleri.",
    tags: ["embedding", "arama", "yüksek kalite"],
    pulls: "5.6M",
    updated: "2024-08",
    capabilities: ["completion"],
    sizes: [
      { tag: "latest", params: "335M", size: "670 MB", sizeBytes: gb(0.65), quant: "F16" },
    ],
  },
  {
    id: "all-minilm",
    name: "All MiniLM",
    description: "Ultra hafif gömme modeli. Hızlı semantik arama ve sınıflandırma.",
    tags: ["embedding", "ultra hafif", "hızlı"],
    pulls: "7.9M",
    updated: "2024-06",
    capabilities: ["completion"],
    sizes: [
      { tag: "latest", params: "23M", size: "45 MB", sizeBytes: gb(0.044), quant: "F16" },
    ],
  },
  {
    id: "snowflake-arctic-embed",
    name: "Snowflake Arctic Embed",
    description: "Snowflake'in gömme modeli. Retrieval benchmarklarında lider performans.",
    tags: ["embedding", "retrieval", "snowflake"],
    pulls: "3.8M",
    updated: "2024-08",
    capabilities: ["completion"],
    sizes: [
      { tag: "xs", params: "23M", size: "46 MB", sizeBytes: gb(0.045), quant: "F16" },
      { tag: "s", params: "33M", size: "67 MB", sizeBytes: gb(0.065), quant: "F16" },
      { tag: "m", params: "110M", size: "229 MB", sizeBytes: gb(0.22), quant: "F16" },
      { tag: "l", params: "335M", size: "670 MB", sizeBytes: gb(0.65), quant: "F16" },
    ],
  },
  {
    id: "wizard-math",
    name: "Wizard Math",
    description: "Matematik problemleri çözmek için özelleştirilmiş model. Adım adım çözüm.",
    tags: ["matematik", "uzman", "muhakeme"],
    pulls: "1.5M",
    updated: "2024-02",
    capabilities: ["completion"],
    sizes: [
      { tag: "7b", params: "7B", size: "3.8 GB", sizeBytes: gb(3.8), quant: "Q4_0" },
      { tag: "13b", params: "13B", size: "7.4 GB", sizeBytes: gb(7.4), quant: "Q4_0" },
      { tag: "70b", params: "70B", size: "39 GB", sizeBytes: gb(39), quant: "Q4_0" },
    ],
  },
  {
    id: "sqlcoder",
    name: "SQLCoder",
    description: "SQL sorgusu üretme uzmanı. Doğal dilden SQL'e çeviri.",
    tags: ["SQL", "veritabanı", "uzman"],
    pulls: "1.2M",
    updated: "2024-03",
    capabilities: ["completion"],
    sizes: [
      { tag: "7b", params: "7B", size: "4.1 GB", sizeBytes: gb(4.1), quant: "Q4_0" },
      { tag: "15b", params: "15B", size: "9.0 GB", sizeBytes: gb(9.0), quant: "Q4_0" },
    ],
  },
  {
    id: "magicoder",
    name: "Magicoder",
    description: "OSS-Instruct ile eğitilmiş kod modeli. Açık kaynak kodlardan öğrenmiş.",
    tags: ["kodlama", "açık kaynak", "yenilikçi"],
    pulls: "1.1M",
    updated: "2024-02",
    capabilities: ["completion"],
    sizes: [
      { tag: "7b", params: "7B", size: "3.8 GB", sizeBytes: gb(3.8), quant: "Q4_0" },
    ],
  },
  {
    id: "dolphin-phi",
    name: "Dolphin Phi",
    description: "Sansürsüz Phi tabanlı model. Küçük boyutta serbest kullanım.",
    tags: ["sansürsüz", "hafif", "phi"],
    pulls: "1.9M",
    updated: "2024-02",
    capabilities: ["completion"],
    sizes: [
      { tag: "2.7b", params: "2.7B", size: "1.6 GB", sizeBytes: gb(1.6), quant: "Q4_0" },
    ],
  },
  {
    id: "stablelm2",
    name: "StableLM 2",
    description: "Stability AI'ın hafif dil modeli. Verimli ve hızlı, genel kullanım.",
    tags: ["stability", "hafif", "verimli"],
    pulls: "2.3M",
    updated: "2024-04",
    capabilities: ["completion"],
    sizes: [
      { tag: "1.6b", params: "1.6B", size: "986 MB", sizeBytes: gb(0.96), quant: "Q4_0" },
      { tag: "12b", params: "12B", size: "7.0 GB", sizeBytes: gb(7.0), quant: "Q4_0" },
    ],
  },
  {
    id: "internlm2",
    name: "InternLM 2",
    description: "Shanghai AI Lab'ın modeli. Güçlü muhakeme ve uzun bağlam desteği.",
    tags: ["çince", "muhakeme", "uzun bağlam"],
    pulls: "1.4M",
    updated: "2024-06",
    capabilities: ["completion"],
    sizes: [
      { tag: "1.8b", params: "1.8B", size: "1.1 GB", sizeBytes: gb(1.1), quant: "Q4_0" },
      { tag: "7b", params: "7B", size: "4.5 GB", sizeBytes: gb(4.5), quant: "Q4_0" },
      { tag: "20b", params: "20B", size: "12 GB", sizeBytes: gb(12), quant: "Q4_0" },
    ],
  },
  {
    id: "glm4",
    name: "GLM 4",
    description: "Zhipu AI'ın çok yetenekli modeli. Çince ve İngilizce'de güçlü performans.",
    tags: ["çince", "zhipu", "çok yönlü"],
    pulls: "1.6M",
    updated: "2024-08",
    capabilities: ["completion", "tools"],
    sizes: [
      { tag: "9b", params: "9B", size: "5.5 GB", sizeBytes: gb(5.5), quant: "Q4_0" },
    ],
  },
  {
    id: "olmo",
    name: "OLMo",
    description: "Allen AI'ın tamamen açık modeli. Eğitim verileri ve kod dahil her şey açık.",
    tags: ["açık kaynak", "araştırma", "şeffaf"],
    pulls: "1.3M",
    updated: "2024-09",
    capabilities: ["completion"],
    sizes: [
      { tag: "1b", params: "1B", size: "696 MB", sizeBytes: gb(0.68), quant: "Q4_0" },
      { tag: "7b", params: "7B", size: "4.0 GB", sizeBytes: gb(4.0), quant: "Q4_0" },
    ],
  },
];
