name: Publish to Winget
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Submit package to Windows Package Manager
        uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: Quacomes.Axiom
          version: ${{ github.event.release.tag_name }}
          installer-url: https://github.com/quacomes-cli/axiom/releases/download/${{ github.event.release.tag_name }}/Axiom_${{ github.event.release.tag_name }}_x64-setup.exe
          token: ${{ secrets.WINGET_TOKEN }}
